// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalculateController from "./calculate_controller"
application.register("calculate", CalculateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProductController from "./product_controller"
application.register("product", ProductController)
